version: '3.9'

services:
  lcl:
    container_name: todo-lcl
    image: todo-lcl
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    ports:
      - 4000:4000
    command: npm run dev