version: '3.9'

volumes:
  db-data:

services:
  client:
    image: node:18
    container_name: app-intro-client
    working_dir: /app
    volumes:
      - ./packages/frontend:/app
      - ./node_modules:/app/node_modules
    ports:
      - 4444:4444
    command: npm run client:dev

  server:
    image: node:18
    container_name: app-intro-server
    working_dir: /app
    volumes:
      - ./packages/backend:/app
      - ./node_modules:/app/node_modules
    ports:
      - 4445:4445
    command: npm run server:dev

  db:
    image: mysql:8.0
    platform: linux/x86_64
    container_name: app-intro-db
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: todo_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - 4500:3306