version: '3.9'

services:
  base:
    image: todo-base
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app

  client:
    image: todo-client
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./packages/frontend:/app
    ports:
      - 4444:8080
    command: npm run client:dev

  server:
    image: todo-server
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./packages/backend:/app
    ports:
      - 4445:4000
    command: npm run server:dev