version: '3.9'

services:
  client:
    image: todo-client
    build:
      context: docker/frontend
      dockerfile: Dockerfile
    volumes:
      - ./packages/frontend:/app
      - ./node_modules:/app/node_modules
    ports:
      - 4444:5173
    command: npm run client:dev

  server:
    image: todo-server
    build:
      context: docker/backend
      dockerfile: Dockerfile
    volumes:
      - ./packages/backend:/app
      - ./node_modules:/app/node_modules
    ports:
      - 4445:4000
    command: npm run server:dev